Варіан 1
Завдання 1



Створіть одновимірний масив (вектор) із арифметичною послідовністю, де кожне
наступне число більше попереднього на 5, починаючи з 3, та виведіть його значення.


In [17]:
import numpy as np
from scipy.stats import gmean

In [32]:
start = 3
step = 5
vector_1 = np.arange(start, start + 5 * step, step)
print("1. Вектор з арифметичною послідовністю (початок=3, крок=5):")
print(vector_1)

1. Вектор з арифметичною послідовністю (початок=3, крок=5):
[ 3  8 13 18 23]


Завдання 2

Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його добутками
кожного числа та його попереднього, починаючи з 1, та виведіть його значення.

In [31]:
elements = np.arange(1, 10) # 1, 2, ..., 9
products = elements * (elements - 1)
matrix_2 = products.reshape(3, 3)
print("\n2. Матриця 3x3 з добутками n * (n-1):")
print(matrix_2)


2. Матриця 3x3 з добутками n * (n-1):
[[ 0  2  6]
 [12 20 30]
 [42 56 72]]


Завдання 3

Створіть масив розміром $3 \times 3$, заповніть його випадковими натуральними числами від 1 до 2 та знайдіть середнє арифметичне його елементів.

In [28]:
matrix_3 = np.random.randint(1, 3, size=(3, 3))
mean_3 = np.mean(matrix_3)
print("\n3. Матриця 3x3 з випадковими числами [1, 2]:")
print(matrix_3)
print(f"Середнє арифметичне: {mean_3}")


3. Матриця 3x3 з випадковими числами [1, 2]:
[[1 2 1]
 [2 2 2]
 [2 1 1]]
Середнє арифметичне: 1.5555555555555556


Завдання 4

Створіть масив розміром $4 \times 4$, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть кількість елементів, що більше 0.5.



In [29]:
matrix_4 = np.random.rand(4, 4)
count_greater_than_0_5 = np.sum(matrix_4 > 0.5)
matrix_4
count_greater_than_0_5

np.int64(6)

Завдання 5

Створіть два одновимірних масиви розміром 7, заповніть їх випадковими цілими числами від -15 до 15 та виконайте на них поелементні операції додавання, віднімання та множення.


In [30]:
size_5 = 7
vector_a = np.random.randint(-15, 16, size=size_5)
vector_b = np.random.randint(-15, 16, size=size_5)

sum_5 = vector_a + vector_b
difference_5 = vector_a - vector_b
product_5 = vector_a * vector_b

print("\n5. Поелементні операції з векторами розміром 7 (цілі [-15, 15]):")
print(f"Вектор A: {vector_a}")
print(f"Вектор B: {vector_b}")
print(f"Сума (A + B): {sum_5}")
print(f"Різниця (A - B): {difference_5}")
print(f"Добуток (A * B): {product_5}")


5. Поелементні операції з векторами розміром 7 (цілі [-15, 15]):
Вектор A: [ 14  10  14  -7   2  -5 -14]
Вектор B: [ -6   7   2  -8  -2  -8 -11]
Сума (A + B): [  8  17  16 -15   0 -13 -25]
Різниця (A - B): [20  3 12  1  4  3 -3]
Добуток (A * B): [-84  70  28  56  -4  40 154]


Завдання 6

Створіть дві матриці $4 \times 4$, заповніть їх довільними цілими числами від 1 до 10 та знайдіть їх добуток.


In [7]:
matrix_a_6 = np.random.randint(1, 11, size=(4, 4))
matrix_b_6 = np.random.randint(1, 11, size=(4, 4))

product_6 = matrix_a_6 @ matrix_b_6

print("\n6. Матричний добуток матриць 4x4 (цілі [1, 10]):")
print("Матриця A:")
print(matrix_a_6)
print("Матриця B:")
print(matrix_b_6)
print("Добуток A @ B:")
print(product_6)


6. Матричний добуток матриць 4x4 (цілі [1, 10]):
Матриця A:
[[ 4  2  3  1]
 [ 5  9  4  8]
 [ 4  6  7 10]
 [ 7  4  4  5]]
Матриця B:
[[10  1  8  1]
 [ 5  8  5  9]
 [ 8  4 10  5]
 [ 5  2  9  3]]
Добуток A @ B:
[[ 79  34  81  40]
 [167 109 197 130]
 [176 100 222 123]
 [147  65 161  78]]


Завдання 7

Створіть дві матриці розміром $4 \times 2$ та $2 \times 5$, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.Результат матиме розмір $4 \times 5$.

In [8]:
matrix_a_7 = np.random.randint(1, 11, size=(4, 2))
matrix_b_7 = np.random.randint(1, 11, size=(2, 5))

product_7 = matrix_a_7 @ matrix_b_7

print("\n7. Матричний добуток матриць 4x2 та 2x5 (цілі [1, 10]):")
print("Матриця A (4x2):")
print(matrix_a_7)
print("Матриця B (2x5):")
print(matrix_b_7)
print("Добуток A @ B (4x5):")
print(product_7)


7. Матричний добуток матриць 4x2 та 2x5 (цілі [1, 10]):
Матриця A (4x2):
[[3 5]
 [3 8]
 [1 1]
 [2 9]]
Матриця B (2x5):
[[ 7  1  9  5 10]
 [ 2  2  1 10  1]]
Добуток A @ B (4x5):
[[ 31  13  32  65  35]
 [ 37  19  35  95  38]
 [  9   3  10  15  11]
 [ 32  20  27 100  29]]


Завдання 8

Створіть матрицю розміром $2 \times 2$, заповніть її випадковими цілими числами в діапазоні від 1 до 12 та знайдіть її обернену матрицю.

In [33]:
while True:
    matrix_8 = np.random.randint(1, 13, size=(2, 2))
    if np.linalg.det(matrix_8) != 0:
        break

inverse_matrix_8 = np.linalg.inv(matrix_8)

print("\n8. Обернена матриця 2x2 (цілі [1, 12]):")
print("Вихідна матриця:")
print(matrix_8)
print("Обернена матриця:")
print(inverse_matrix_8)


8. Обернена матриця 2x2 (цілі [1, 12]):
Вихідна матриця:
[[8 7]
 [8 5]]
Обернена матриця:
[[-0.3125  0.4375]
 [ 0.5    -0.5   ]]


Завдання 9

Створіть матрицю розміром $3 \times 3$, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [34]:
matrix_9 = np.random.rand(3, 3)
transposed_matrix_9 = matrix_9.T

print("\n9. Транспонування матриці 3x3 (дійсні [0, 1]):")
print("Вихідна матриця:")
print(matrix_9)
print("Транспонована матриця:")
print(transposed_matrix_9)


9. Транспонування матриці 3x3 (дійсні [0, 1]):
Вихідна матриця:
[[0.96917454 0.5574923  0.83452615]
 [0.93813225 0.93546278 0.56477636]
 [0.14140994 0.8567334  0.56521191]]
Транспонована матриця:
[[0.96917454 0.93813225 0.14140994]
 [0.5574923  0.93546278 0.8567334 ]
 [0.83452615 0.56477636 0.56521191]]


Завдання 10

Створіть матрицю розміром $3 \times 4$ та вектор розміром $4 \times 1$, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1 і знайдіть добуток матриці на вектор.

In [35]:
matrix_10 = np.random.rand(3, 4)
vector_10 = np.random.rand(4, 1)

product_10 = matrix_10 @ vector_10

print("\n10. Добуток матриці 3x4 на вектор 4x1 (дійсні [0, 1]):")
print("Матриця 3x4:")
print(matrix_10)
print("Вектор 4x1 (стовпчик):")
print(vector_10)
print("Добуток (3x1):")
print(product_10)


10. Добуток матриці 3x4 на вектор 4x1 (дійсні [0, 1]):
Матриця 3x4:
[[0.9827921  0.89904699 0.18618988 0.27378402]
 [0.8599133  0.94214407 0.99221925 0.22304661]
 [0.77082234 0.56365753 0.9279154  0.72603596]]
Вектор 4x1 (стовпчик):
[[0.44648327]
 [0.79878866]
 [0.55417134]
 [0.5011758 ]]
Добуток (3x1):
[[1.39734379]
 [1.79815594]
 [1.67249829]]


Завдання 11

Створіть матрицю розміром $2 \times 3$ та вектор розміром 3 (рядок-вектор), заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [36]:
matrix_11 = np.random.rand(2, 3)
vector_11 = np.random.randint(1, 11, size=3)

product_11 = matrix_11 @ vector_11

print("\n11. Добуток матриці 2x3 на вектор 3:")
print("Матриця 2x3 (дійсні [0, 1]):")
print(matrix_11)
print("Вектор 3 (цілі [1, 10]):")
print(vector_11)
print("Добуток (вектор 2):")
print(product_11)


11. Добуток матриці 2x3 на вектор 3:
Матриця 2x3 (дійсні [0, 1]):
[[0.9406245  0.83086694 0.04364821]
 [0.24383188 0.43045014 0.42969368]]
Вектор 3 (цілі [1, 10]):
[1 4 6]
Добуток (вектор 2):
[4.52598151 4.54379452]


Завдання 12

Створіть дві матриці розміром $4 \times 4$, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть різницю всіх елементів обох матриць (тобто $\sum A_{ij} - \sum B_{ij}$


In [37]:
matrix_a_12 = np.random.randint(1, 11, size=(4, 4))
matrix_b_12 = np.random.randint(1, 11, size=(4, 4))

difference_of_sums_12 = np.sum(matrix_a_12 - matrix_b_12)

print("\n12. Різниця всіх елементів двох матриць 4x4 (цілі [1, 10]):")
print("Матриця A:")
print(matrix_a_12)
print("Матриця B:")
print(matrix_b_12)
print(f"Сума елементів A: {np.sum(matrix_a_12)}")
print(f"Сума елементів B: {np.sum(matrix_b_12)}")
print(f"Різниця всіх елементів (Сума(A) - Сума(B)): {difference_of_sums_12}")


12. Різниця всіх елементів двох матриць 4x4 (цілі [1, 10]):
Матриця A:
[[1 6 2 2]
 [7 8 6 3]
 [1 8 6 8]
 [9 5 6 8]]
Матриця B:
[[ 3  1  7  5]
 [10  5  7  3]
 [ 7  6  3  3]
 [10  1  2  8]]
Сума елементів A: 86
Сума елементів B: 81
Різниця всіх елементів (Сума(A) - Сума(B)): 5


Завдання 13

Створіть дві матриці розміром $3 \times 3$, заповніть їх випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть суму їх елементів (тобто $\sum (A_{ij} + B_{ij})$

In [38]:
matrix_a_13 = np.random.uniform(-1, 1, size=(3, 3))
matrix_b_13 = np.random.uniform(-1, 1, size=(3, 3))

sum_of_elements_13 = np.sum(matrix_a_13 + matrix_b_13)

print("\n13. Сума всіх елементів двох матриць 3x3 (дійсні [-1, 1]):")
print("Матриця A:")
print(matrix_a_13)
print("Матриця B:")
print(matrix_b_13)
print(f"Сума всіх елементів: {sum_of_elements_13}")


13. Сума всіх елементів двох матриць 3x3 (дійсні [-1, 1]):
Матриця A:
[[-7.99938916e-01 -4.75077905e-04  4.71158336e-01]
 [-8.19751524e-01  2.31646230e-01  8.76890930e-02]
 [ 2.02989070e-01  9.66272472e-01 -4.56322987e-02]]
Матриця B:
[[-0.77694227 -0.35637682 -0.86930172]
 [ 0.46801916 -0.49542864 -0.20351543]
 [ 0.87542665 -0.51736748  0.32943959]]
Сума всіх елементів: -1.2520895636588567


Завдання 14

Створіть матрицю розміром $3 \times 3$, заповніть її випадковими дійсними числами в діапазоні від -3 до 3 та знайдіть кількість парних елементів матриці.

In [39]:
matrix_14_int = np.random.randint(-3, 4, size=(3, 3)) # Цілі [-3, 3]

count_even_14 = np.sum(matrix_14_int % 2 == 0)

print("\n14. Кількість парних елементів у матриці 3x3 (цілі [-3, 3]):")
print("Матриця:")
print(matrix_14_int)
print(f"Кількість парних елементів: {count_even_14}")


14. Кількість парних елементів у матриці 3x3 (цілі [-3, 3]):
Матриця:
[[ 2 -1  0]
 [-1  3 -3]
 [-3  1  3]]
Кількість парних елементів: 2


Завдання 15

Створіть матрицю розміром $5 \times 5$, заповніть її випадковими дійсними числами в діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик, що містить середнє геометричне значення елементів кожного рядка матриці.

In [40]:
matrix_15 = np.random.uniform(0.01, 0.51, size=(5, 5))

mean_geometric_row = gmean(matrix_15, axis=1)

vector_column_15 = mean_geometric_row.reshape(-1, 1)

print("\n15. Вектор-стовпчик середнього геометричного (Матриця 5x5, дійсні [0.01, 0.51]):")
print("Матриця:")
print(matrix_15)
print("Вектор-стовпчик середніх геометричних значень рядків (5x1):")
print(vector_column_15)


15. Вектор-стовпчик середнього геометричного (Матриця 5x5, дійсні [0.01, 0.51]):
Матриця:
[[0.04410797 0.13875663 0.45178033 0.2625719  0.0418544 ]
 [0.24366934 0.27634828 0.11382042 0.0929177  0.0203967 ]
 [0.32794607 0.42477192 0.08820431 0.31842823 0.04036773]
 [0.20767448 0.1530553  0.4824832  0.39794141 0.46983612]
 [0.12786568 0.16158254 0.28714946 0.45381733 0.07401028]]
Вектор-стовпчик середніх геометричних значень рядків (5x1):
[[0.12489282]
 [0.10775247]
 [0.17365959]
 [0.31009577]
 [0.18192229]]


Висновок:виконана робота підтверджує, що бібліотека NumPy є найважливішим інструментом для ефективних числових обчислень та маніпуляцій з масивами (векторами й матрицями) у Python. Успішно реалізовано створення масивів за правилами, виконання поелементних операцій, складних матричних обчислень (добуток, обернення) та статистичний аналіз даних. NumPy значно прискорює та спрощує завдання лінійної алгебри та обробки даних.